version: '3.3'
services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: php73
    depends_on:
      - db
    volumes: 
      - ./:/var/www/html/
    ports:
      - 8000:80
  db:
    container_name: mysql8
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: my_db
      MYSQL_USER: root
    ports:
      - 33086:3306
  composer:
    restart: 'no'
    image: composer
    command: install
    volumes:
      - ./:/var/www/html/
