openapi: 3.0.0
info:
  description: |
    An API for integrating Slack's services with Wikpedia.
  version: '1.0.0'
  title: stack-slack-slash API
  license:
    name: Proprietary
    url: 'https://github.com/lucas0000miranda/stack-slack-slash'
  contact:
    name: Software Tree
    email: 'lucas0000miranda@outlook.com'
tags:
  - name: api
    description: Helpers for api
  - name: Wikipedia API
    description: Wikipedia API Management
paths:
  /:
    get:
      summary: Application manifest
      description: Returns a manifest of the API
      tags:
        - api
      operationId: index
      responses:
        '200':
          description: The application's manifest
  /_healthcheck:
    get:
      summary: Application healthcheck
      description: Returns a response if the application is reachable.
      tags:
        - api
      operationId: healthcheck
      responses:
        '200':
          description: The application is responding
  /search:
    get:
      tags:
        - Wikipedia API
      summary: Get seach from wikipedia
      description: Get a mount of json info search from Wikipedia
      operationId: get-search
      parameters:
        - in: query
          name: action
          schema:
            type: string
          required: true
          description: The Wikipedia function api that it'll be use
          example: 'opensearch'
        - in: query
          name: search
          schema:
            type: string
          required: true
          description: What will be looking for wikipidia search
          example: 'airship'
        - in: query
          name: format
          schema:
            type: string
          required: true
          description: The extension of data that it'll be received
          example: 'json, xml ... etc'
        - in: query
          name: limit
          schema:
            type: integer
          required: true
          description: Limit how many results it'll be returned.
          example: 4,40,100
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SearchResponse'
                example: ['title', ['title'], ['summary'], ['url']]
        '400':
          description: Bad Request
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ValidationError'
        '401':
          description: Unauthorized
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/UnauthorizedError'
components:
  schemas:
    SearchResponse:
      type: array
      items:
        properties:
          title:
            type: string
            example: 'airship'
            uniqueItems: true
          summary:
            type: string
            example: 'An airship or dirigible is a .. .'
            uniqueItems: true
          url:
            type: string
            example: 'https://en.wikipedia.org/wiki/Airship'
            uniqueItems: true
    UnauthorizedError:
      description: Authentication information is missing or invalid
      required:
        - title
        - status
        - detail
      properties:
        type:
          description: Authentication information is missing or invalid.(description by Linio)".
          type: string
        title:
          description: |
            A short, human-readable summary of the problem
            type.  It SHOULD NOT change from occurrence to occurrence of the
            problem, except for purposes of localization (description by Linio)
          type: string
          example: Unauthorized
        status:
          description: The HTTP status code generated by the origin server for this occurrence of the problem.
          type: integer
          format: int32
          example: 401
        detail:
          description: A human-readable explanation specific to this occurrence of the problem.
          type: string
          example: Unauthorized.
        invalid-params:
          description: List of invalid parameters and respective errors
          type: array
          items:
            required:
              - reason
            properties:
              reason:
                description: Token invalid
                type: string
                example: Invalid token
    ValidationError:
      required:
        - title
        - status
        - detail
      properties:
        type:
          description: |
            A URI reference [RFC3986] that identifies the
            problem type.  This specification encourages that, when
            dereferenced, it provide human-readable documentation for the
            problem type (e.g., using HTML [W3C.REC-html5-20141028]).  When
            this member is not present, its value is assumed to be
            "about:blank.(description by Linio)".
          type: string
        title:
          description: |
            A short, human-readable summary of the problem
            type.  It SHOULD NOT change from occurrence to occurrence of the
            problem, except for purposes of localization (description by Linio)
          type: string
          example: Invalid request parameters
        status:
          description: The HTTP status code generated by the origin server for this occurrence of the problem.
          type: integer
          format: int32
          example: 400
        detail:
          description: A human-readable explanation specific to this occurrence of the problem.
          type: string
          example: Invalid request paramters [orderNo].
        invalid-params:
          description: List of invalid parameters and respective errors
          type: array
          items:
            required:
              - name
              - reason
            properties:
              name:
                description: Field name
                type: string
                example: search
              reason:
                description: Validation error details
                type: string
                example: Invalid search
